"""Create settings table

Revision ID: 7a1f524f5719
Revises: 5fd7736cdd30
Create Date: 2026-07-10 11:14:22.086884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1f524f5719'
down_revision = '5fd7736cdd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_name', sa.String(length=100), nullable=True),
    sa.Column('default_due_days', sa.Integer(), nullable=True),
    sa.Column('fine_per_day', sa.Float(), nullable=True),
    sa.Column('allow_manual_due_date', sa.Boolean(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('auto_create_category', sa.Boolean(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
